Add api calls for profile photo.
smartface/sample-mcommerce pull request #30
Opened 2022-01-25 15:01 UTC by fuatguzel

FYI: dialog show not working!

2022-01-25 15:19 UTC, alimoncul requested changes

2022-01-25 15:19 UTC, alimoncul commented on scripts/components/FlAccountUser.ts
>      set userImage(value: any) {
type yazalim

2022-01-25 15:19 UTC, alimoncul commented on scripts/pages/pgLogin.ts
> +                    if (this.router instanceof NativeStackRouter) {
bu degisiklik bilerek mi yapildi

2022-01-25 15:19 UTC, alimoncul commented on scripts/pages/pgAccount.ts
> +    async fetchUserProfileImage() {
kaldiralim

2022-01-25 15:19 UTC, alimoncul commented on scripts/pages/pgAccount.ts
> +import { getProfileImage, getProfileImageUrl, putProfileImage } from 'service/commerce';
getProfileImage silelim

2022-01-25 15:19 UTC, alimoncul commented on scripts/service/commerce.ts
> +export async function getProfileImage(): Promise<any> {
silelim

2022-01-25 15:22 UTC, fuatguzel commented on scripts/pages/pgLogin.ts
> +                    if (this.router instanceof NativeStackRouter) {
Evet dismiss olmasi gerekiyor. push calismiyordu.

2022-01-26 05:54 UTC, alimoncul approved these changes

2022-01-26 05:55 UTC, merged